name: Binary Test

on: [push, pull_request]

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make binary executable
      run: chmod +x ./bin/sigtrap_v1.0

    - name: Run binary with test
      run: |
        ./bin/sigtrap_v1.0 --help || echo "[OK] Help displayed"
